import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by Payload — regenerate rather than edit.
      "src/payload-types.ts",
      "src/app/(payload)/**",
    ],
  },
  // Type checking is handled by `tsc --noEmit`, so this stays on the fast,
  // non-type-aware Next rules.
  ...compat.extends("next/core-web-vitals"),
];
